### ISSUE TITLE
WAN setup

### ISSUE THREAD

**Issue by vencax** [lorenzschmid/pyRN2483#3]
Hi, have you tried setting up a WAN device? Would you consider useful methods like:
- def config_otaa(self, appkey=None, appeui=None):
- def config_abp(self, nwskey=None, appskey=None, devaddr=None):

similar to: https://github.com/alexantoniades/python-RN2483/blob/master/rn2483.py

**Comment by lorenzschmid** [comment]
Hi @vencax 

To be honest this whole repo was more an afternoon project to setup a temperature sensor in the lake. So we haven't spend many thoughts on additional features such as OTA configuration (and I haven't touched the code in along time...). I don't mind adding new features but why not use [alexantoniades/python-RN2483](https://github.com/alexantoniades/python-RN2483/) instead of reimplementing it here?

Best, Lorenz

**Comment by vencax** [comment]
Hi Lorenz, it is because https://github.com/alexantoniades/python-RN2483/ does not count with running in uPython. I have opened a PR (https://github.com/lorenzschmid/pyRN2483/pull/4) with what I have got and you can decide what to do with it. Thanks, closing
